name: Cfn-guard scan

on:
  pull_request:
    paths:
      - "templates/**"
      - "*.yml"

jobs:
  cfn-guard:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      checks: write

    steps:
      - name: Checkout implementation repo
        uses: actions/checkout@v3
      - name: Checkout cfnguard-action repo
        uses: actions/checkout@v3
        with:
          repository: Shankhajit-Sen/cfnguard-action
          path: "cfnguard-action/guard-actions@v1"
      - name: Debug Paths
        run: |
          echo "Data path: ${{ github.workspace }}/templates"
      - name: Check cfn-guard rules
        uses: Shankhajit-Sen/cfnguard-action/guard-actions@v2
        with: # Path to the rules in the cfnguard-action repo
          data: './templates'
